# Generated by Django 6.1 on 2026-09-13 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('education', 'Education'), ('certification', 'Certification'), ('competition', 'Competition')], default='education', max_length=20)),
                ('year', models.CharField(max_length=50)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
